[package]
name = "zagreus-generator"
version = "0.0.4"
authors = ["Mario Kaufmann <mario.kaufmann@bluemail.ch>"]
edition = "2021"

[dependencies]
log = "0.4.14"
reqwest = { version = "0.11.8", features = ["blocking", "multipart"] }
serde = "1.0.132"
serde_derive = "1.0.132"
serde_json = "1.0.73"
serde_yaml = "0.8.23"
xml-rs = "0.8.4"
zip = "0.5.13"
walkdir = "2.3.2"
structopt = "0.3.25"
notify = "4.0.17"

[dependencies.log4rs]
version = "1.0.0"
default-features = false
features = ["console_appender"]

[dev-dependencies]
rand = "0.8.4"
